name: slack-approval-with-plan
description: Custom action to send approval request to Slack from GitHub Actions
author: varu3
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: plus
  color: green

